version: '3'
services:

  previewer:
    container_name: previewer
    build:
      context: ../..
      dockerfile: ./build/previewer/Dockerfile
    restart: always
    volumes:
      - ../../configs/previewer:/configs/previewer
    command: sh -c "sleep 10 && ./opt/app/bin --config configs/previewer/config.json"
    ports:
      - "8888:80"
    networks:
      - previewer_network

networks:
  previewer_network:
    driver: bridge